input {
  tcp {
    port => 5000
    codec => json_lines
  }
}

filter {
  mutate {
    rename => { "service" => "service_name" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ecomm-logs-%{service_name}-%{+YYYY.MM.dd}"
  }
}
