server:
  port: 8889

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/kariukialex999/ApiGateway.git
          default-label: main
          clone-on-start: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"