server:
  port: 8080

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: Inventory-service
          uri: lb://Inventory-service
          predicates:
            - Path=/inventory/**

        - id: OrderService
          uri: lb://OrderService
          predicates:
            - Path=/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    prefer-ip-address: true
