server:
  port: 8080

spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: inventory-service
          uri: lb://inventory-service-lb
          predicates:
            - Path=/inventory/**

        - id: order-service
          uri: lb://order-service-lb
          predicates:
            - Path=/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
